title: Bryan Reynolds # your name (or website title) here
logo: "/Images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent PhD graduate in Physics from the Ohio State University. My graduate research focused on experimental high energy physics, where I used data analysis and advanced computational techniques to study particle collisions to help learn about our universe.
  <br><br>
  Now I'm excited to use my programming and analysis skills to start my career in data science! 
  <br><br>
  <a href="https://www.linkedin.com/in/bryanreynolds93/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

